### ISSUE TITLE
2014.4.10 之后我们会关闭这个接口

### ISSUE THREAD

**Issue by jacobbubu** [sanddudu/nextday-desktop#1]

**Comment by sanddudu** [comment]
感谢提醒

-----原始邮件-----
发件人: "jacobbubu" notifications@github.com
发送时间: ‎2014/‎4/‎2 12:55
收件人: "sanddudu/nextday-desktop" nextday-desktop@noreply.github.com
主题: [nextday-desktop] 2014.4.10 之后我们会关闭这个接口 (#1)

**Comment by sanddudu** [comment]
不过我不知道目前官方对我这个应用是持什么态度。
如果你们不希望我继续做下去，或者开源，可以直接联系我。
如果没有表态的话，我说不定什么时候能找到一个新的接口呢。

以上

**Comment by sanddudu** [comment]
另外我希望你们能把网页版的修一下

**Comment by jacobbubu** [comment]
网页修好了。

Nextday 在4.0 之后由于增加了定制和定时发送礼物的功能，所以原来仅仅是静态数据接口的方式就不够了。4.0 之后的接口是基于Websocket的。由于 Nextday 没有要求用户登录的过程，因此就需要严格控制协议的安全以及访问的客户端（通过客户端证书来控制）。

所有静态接口只是为了兼容 4.0 之前的版本，等老版本用户数量降到一定程度就会放弃。

功能变了，安全需求变了，协议也变了，所以很遗憾，其他使用老的静态协议的应用就只能放弃了。

**Comment by sanddudu** [comment]
Done！

**Comment by sanddudu** [comment]
我希望你们能至少在官微里提一下接口关闭的事情
用户不是给你们这么烧着玩的
另外公司主页一直都是IIS的默认页面

**Comment by jacobbubu** [comment]
这个接口由于可以看到未来的数据，所以一直是一个漏洞，原本没人发现也就算了。现在既然被发现了，就要考虑解决方法。我们是一家小公司，也不以此盈利，因此没有这个成本同时维护多个手机操作系统的版本，两害相权之下只好放弃一端。

另外，公司官网的DNS改了几天，可能还没复制到你那里。现在访问 nxmix.com 应该跳到 nextday的首页，在北京上海测试已经是如此，不知道你在哪里?

**Comment by sanddudu** [comment]
我现在访问官网已经跳转了。
以前的接口我直接访问之后的数据好像都是404，不知道是怎么看到未来的数据的。
另外数据基本都是提前更新上去的，作为静态接口如果没有任何限制能看到估计是应该的。
之前的源代码很大程度上可能暴露了这个接口，不过目前代码已经换成了混淆之后的，而且也把接口换成不会牵涉到官方的接口。
不管怎么说，权衡利弊也罢，关了接口这种事情也应该让用户知晓，而不是变成现在我这样的第三方应用的开发者上去解释，这也不是我的义务，不过我觉得应该有人给他们一个解释。

**Comment by jacobbubu** [comment]
我们会对Windows Phone的用户解释原因，但是Nextday Desktop 为什么不能用我们是不会解释的，毕竟我们没有公开过这个接口，也没有Nextday “第三方应用”的概念。

当年开发这个接口的前辈应该是没有想到还会有人关心Nextday的接口，所以做成静态的了。由于编辑每次都是仅仅提前上传几天的数据，所以看比较靠后的数据是会返回404，但是起码第二天的数据是可以拿到的。这个老接口根本无需看源代码就可获取，用Windows Phone的同学抓个包就都看到了。至于nextday.im这个网站，则根本没用到任何API，只是在后台纯静态地生成了网页内容，然后每天自动部署到CDN上。所谓混淆只是加了minification以减少网页流量，因为载入每日图片完成前显示的的黑白占位点阵图是直接dataUri到html文本中的。

**Comment by sanddudu** [comment]
NextDay-Desktop 不用解释，没有这个必要。
另外混淆是指 NextDay-Desktop 新版本的代码混淆。
