### ISSUE TITLE
NextDay API请求地址失效！

### ISSUE THREAD

**Issue by homeboyStudio** [sanddudu/nextday-desktop#11]
您好~我的App iOS端使用的是http://nichijou.in/LastDay/yyyy/mm/dd.json这个来请求数据，之前都是正常，每天的数据都能拉下来。但就在最近这个API好像失效了，我用Post Man测试返回的是200，但是数据错误，如果是停止更新或者API迁移请告知一下给我，O(∩_∩)O谢谢。

**Comment by sanddudu** [comment]
抱歉，由于疏忽忘记续费域名了...
今天之内应该能恢复

**Comment by homeboyStudio** [comment]
木有关系，app还在开发中，话说桌面版的功能已经很完善了，在此感谢你无私奉献的精神XD！！太感动了，需要赞助域名续费的给吼一声！！(_^__^_) 嘻嘻……

**Comment by sanddudu** [comment]
已恢复
