### ISSUE TITLE
hi, 请问现在每天图片都刷不出来了~是服务器到期了吗？

### ISSUE THREAD

**Issue by homeboyStudio** [sanddudu/nextday-desktop#13]
hi, 请问现在每天图片都刷不出来了~是服务器到期了吗？很喜欢这个桌面应用，希望能恢复~可以赞助嘻嘻

**Comment by sanddudu** [comment]
很抱歉，由于前一段时间域名商停止了 DNS 服务，导致之后域名 DNS 服务被不法人士抢注，域名的相关记录被修改，目前正在恢复当中，可能需要 3 天左右的时间

**Comment by sanddudu** [comment]
目前 DNS 记录已经全部修改完成，等待各地的服务器进行刷新，最长需要 3 天的时间

**Comment by homeboyStudio** [comment]
嗯，感谢一直坚持着，还有你们的作品~很棒！
