### ISSUE TITLE
NextDay 已经提供官方 API 了。

### ISSUE THREAD

**Issue by jacobbubu** [sanddudu/nextday-desktop#5]
文档在这里: https://github.com/NXMIX/nextday-public-api
需要发邮件到 support@nextday.im 来申请 partner  key。
应某个商业合作方的要求，NextDay 的 API 不能被用于 Android 桌面类和壁纸类应用，因此加了限制。其他形式的客户端都是可以申请的。
原有能够访问到的 http://nextday.nxmix.com 的访问方式将在11月份关闭。

而且，随着 NextDay 新版本的发布，更高清晰度的图片、缩率图和视频也被引入，这是老 API 所不包含的。

**Comment by sanddudu** [comment]
已申请，谢谢提醒

**Comment by jacobbubu** [comment]
已发放，节日愉快!
